CREATE TABLE IF NOT EXISTS COURSE (

    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME NOT NULL VARCHAR(100),
    DESCRIPTION VARCHAR(200),
    TOTAL_DURATION DOUBLE,
    USER_ID INT NOT NULL,
    PROGRAM_ID INT NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    FOREIGN KEY(PROGRAM_ID) REFERENCES PROGRAM(ID)
 )
