CREATE TABLE IF NOT EXISTS COURSE (

    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200),
    TOTAL_DURATION DOUBLE,
    USER_ID BIGINT NOT NULL,
    PROGRAM_ID BIGINT NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    FOREIGN KEY(PROGRAM_ID) REFERENCES PROGRAM(ID)
 );
