create table if not exists APPLICATION (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    STATUS VARCHAR(50) NOT NULL,
    COURSE_IDEA VARCHAR(50),
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID)
        REFERENCES USER(ID)
)