CREATE TABLE IF NOT EXISTS FEEDBACK
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    LESSON_ID BIGINT NOT NULL,
    TITLE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    FOREIGN KEY (LESSON_ID) REFERENCES LESSON (ID)
);
