CREATE TABLE IF NOT EXISTS APPLICATION_STATUS (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STATUS VARCHAR(50) NOT NULL
);

INSERT INTO APPLICATION_STATUS VALUES(NULL, 'PENDING');
INSERT INTO APPLICATION_STATUS VALUES(NULL, 'REJECTED');
INSERT INTO APPLICATION_STATUS VALUES(NULL, 'APPROVED');
