INSERT into learning_platform.users values(null,'Cristina', 'Popescu', 'cristina.popescu@accesa.eu', 'www.server.com/user', '!123Password$');
INSERT into learning_platform.users values(null, 'Andrei', 'Tigan', 'andrei.tigan@accesa.eu', 'www.server.com/user2', '!123Password$');
INSERT into learning_platform.users values(null, 'Cristi (Dan)', 'Flore', 'dan.flore@accesa.eu', 'www.server.com/user3', '!123Password$');
INSERT into learning_platform.users values(null, 'Dan', 'Goia', 'dan.goia@accesa.eu', 'www.server.com/user4', '!123Password$');
INSERT into learning_platform.users values(null, 'Darius', 'Has', 'darius.has@accesa.eu', 'www.server.com/user5', '!123Password$');
INSERT into learning_platform.users values(null, 'Doru', 'Varga', 'doru.varga@accesa.eu', 'www.server.com/user6', '!123Password$');
INSERT into learning_platform.users values(null, 'Madalin', 'Sava', 'madalin.sava@accesa.eu', 'www.server.com/user7', '!123Password$');
INSERT into learning_platform.users values(null, 'Marius', 'Petrut', 'marius.petrut@accesa.eu', 'www.server.com/user8', '!123Password$');
INSERT into learning_platform.users values(null, 'Oana', 'Pantea', 'oana.pantea@accesa.eu', 'www.server.com/user9', '!123Password$');
INSERT into learning_platform.users values(null, 'Raluca', 'Gabor', 'raluca.gabor@accesa.eu', 'www.server.com/user10', '!123Password$');