create table if not exists APPLICATION (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    COURSE_IDEA VARCHAR(50),
    USER_ID BIGINT NOT NULL,
    APPLICATION_STATUS_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID)
        REFERENCES USER(ID),
    FOREIGN KEY (APPLICATION_STATUS_ID)
        REFERENCES APPLICATION_STATUS(ID)
)