CREATE TABLE IF NOT EXISTS QUIZ_ITEM (

    ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
--    QUIZ_ID int NOT NULL,
    QUESTION varchar(255) NOT NULL,
    QUIZ_ITEM_TYPE_ID bigint NOT NULL,
--    FOREIGN KEY(QUIZ_ID) REFERENCES QUIZ(ID)
    FOREIGN KEY(QUIZ_ITEM_TYPE_ID) REFERENCES QUIZ_ITEM_TYPE(ID)

);