CREATE TABLE IF NOT EXISTS ANSWER (

    ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUIZ_ITEM_ID bigint NOT NULL,
    ANSWER_TEXT varchar(255) NOT NULL,
    CORRECT_ANSWER bool NOT NULL,
    FOREIGN KEY (QUIZ_ITEM_ID) references QUIZ_ITEM(ID)
);