CREATE TABLE IF NOT EXISTS USERANSWER (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ANSWER_ID BIGINT NOT NULL,
    USER_ANSWER_TEXT VARCHAR(255) NOT NULL,
--    USER_ID INT NOT NULL,
--    FOREIGN KEY (USER_ID) REFERENCES INTERNS(ID),
    FOREIGN KEY (ANSWER_ID) REFERENCES ANSWER(ID)
);