CREATE TABLE IF NOT EXISTS USERANSWER (
    ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ANSWER_ID bigint NOT NULL,
    USER_ANSWER_TEXT varchar(255) NOT NULL,
--    USER_ID int NOT NULL,
--    FOREIGN KEY (USER_ID) references INTERNS(ID),
    FOREIGN KEY (ANSWER_ID) references ANSWER(ID)
);