
CREATE TABLE IF NOT EXISTS PROGRAM
(
    ID                  bigint      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME                varchar(30) NOT NULL,
    DESCRIPTION         varchar(100),
    START_DATE          DATE,
    END_DATE            DATE,
    COMPETENCE_AREA_ID  bigint
);
ALTER TABLE PROGRAM ADD FOREIGN KEY (COMPETENCE_AREA_ID) REFERENCES COMPETENCE_AREA(ID);
