CREATE TABLE IF NOT EXISTS ENROLLMENT
(
    USER_ID     bigint NOT NULL,
    PROGRAM_ID  bigint NOT NULL,
    CONSTRAINT USER_PROGRAM PRIMARY KEY (USER_ID, PROGRAM_ID)
);
 ALTER TABLE ENROLLMENT ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID);
 ALTER TABLE ENROLLMENT ADD FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(ID);
